# Generated by Django 4.1.5 on 2023-01-06 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crud',
            old_name='keterangan',
            new_name='club',
        ),
        migrations.RenameField(
            model_name='crud',
            old_name='lokasi',
            new_name='nama_pemain',
        ),
        migrations.RenameField(
            model_name='crud',
            old_name='nama',
            new_name='tahun_join',
        ),
        migrations.RenameField(
            model_name='maps',
            old_name='kode',
            new_name='club',
        ),
    ]
